info:
  component: 'API de Lista de Contatos'
  build:
    version: '@project.version@'
    name: '@project.name@'


server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,env
  security:
    enable: false

---   
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true