DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS contact;

CREATE TABLE person
(
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(255),
	created_at TIMESTAMP,
	modified_at TIMESTAMP
);

CREATE TABLE contact
(
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	person_id BIGINT NOT NULL,
	type VARCHAR(255),
	value VARCHAR(255),
	created_at TIMESTAMP,
	modified_at TIMESTAMP
);

ALTER TABLE contact
	ADD FOREIGN KEY (person_id)
	REFERENCES person(id);